# Generated by Django 4.1.1 on 2022-09-16 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sub_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.secondcategory')),
            ],
        ),
    ]
